cd c:\work\monti\src\cd1\data\640\mul
copy /b C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin+C:\Work\monti\src\cd1\xzip\_$hex$t_header.xhd+board\board.png C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin
copy /b C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin+C:\Work\monti\src\cd1\xzip\_$hex$t_header.xhd+board\board_zoom.png C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin
copy /b C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin+C:\Work\monti\src\cd1\xzip\_$hex$t_header.xhd+board\backhole.png C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin
copy /b C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin+C:\Work\monti\src\cd1\xzip\_$hex$t_header.xhd+board\backhole_zoom.png C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin
copy /b C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin+C:\Work\monti\src\cd1\xzip\_$hex$t_header.xhd+board\woodtile128.png C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin
copy /b C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin+C:\Work\monti\src\cd1\xzip\_$hex$t_header.xhd+cards\card10.png C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin
copy /b C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin+C:\Work\monti\src\cd1\xzip\_$hex$t_header.xhd+cards\card09.png C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin
copy /b C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin+C:\Work\monti\src\cd1\xzip\_$hex$t_header.xhd+cards\card08.png C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin
copy /b C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin+C:\Work\monti\src\cd1\xzip\_$hex$t_header.xhd+cards\card07.png C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin
copy /b C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin+C:\Work\monti\src\cd1\xzip\_$hex$t_header.xhd+cards\card06.png C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin
copy /b C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin+C:\Work\monti\src\cd1\xzip\_$hex$t_header.xhd+cards\card05.png C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin
copy /b C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin+C:\Work\monti\src\cd1\xzip\_$hex$t_header.xhd+cards\card04.png C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin
copy /b C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin+C:\Work\monti\src\cd1\xzip\_$hex$t_header.xhd+cards\card03.png C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin
copy /b C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin+C:\Work\monti\src\cd1\xzip\_$hex$t_header.xhd+cards\card02.png C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin
copy /b C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin+C:\Work\monti\src\cd1\xzip\_$hex$t_header.xhd+cards\card01.png C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin
copy /b C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin+C:\Work\monti\src\cd1\xzip\_$hex$t_header.xhd+cards\card10_zoom.png C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin
copy /b C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin+C:\Work\monti\src\cd1\xzip\_$hex$t_header.xhd+cards\card09_zoom.png C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin
copy /b C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin+C:\Work\monti\src\cd1\xzip\_$hex$t_header.xhd+cards\card08_zoom.png C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin
copy /b C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin+C:\Work\monti\src\cd1\xzip\_$hex$t_header.xhd+cards\card07_zoom.png C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin
copy /b C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin+C:\Work\monti\src\cd1\xzip\_$hex$t_header.xhd+cards\card06_zoom.png C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin
copy /b C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin+C:\Work\monti\src\cd1\xzip\_$hex$t_header.xhd+cards\card05_zoom.png C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin
copy /b C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin+C:\Work\monti\src\cd1\xzip\_$hex$t_header.xhd+cards\card04_zoom.png C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin
copy /b C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin+C:\Work\monti\src\cd1\xzip\_$hex$t_header.xhd+cards\card03_zoom.png C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin
copy /b C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin+C:\Work\monti\src\cd1\xzip\_$hex$t_header.xhd+cards\card02_zoom.png C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin
copy /b C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin+C:\Work\monti\src\cd1\xzip\_$hex$t_header.xhd+cards\card01_zoom.png C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin
copy /b C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin+C:\Work\monti\src\cd1\xzip\_$hex$t_header.xhd+chip\chip_shadow.png C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin
copy /b C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin+C:\Work\monti\src\cd1\xzip\_$hex$t_header.xhd+chip\chip_shadow_zoom.png C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin
copy /b C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin+C:\Work\monti\src\cd1\xzip\_$hex$t_header.xhd+chip\chip.png C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin
copy /b C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin+C:\Work\monti\src\cd1\xzip\_$hex$t_header.xhd+chip\chip_zoom.png C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin
copy /b C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin+C:\Work\monti\src\cd1\xzip\_$hex$t_header.xhd+perls\perl.png C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin
copy /b C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin+C:\Work\monti\src\cd1\xzip\_$hex$t_header.xhd+perls\perl_shadow_zoom.png C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin
copy /b C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin+C:\Work\monti\src\cd1\xzip\_$hex$t_header.xhd+perls\perl_shadow.png C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin
copy /b C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin+C:\Work\monti\src\cd1\xzip\_$hex$t_header.xhd+perls\perl_zoom.png C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin
copy /b C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin+C:\Work\monti\src\cd1\xzip\_$hex$t_header.xhd+box.png C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin
copy /b C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin+C:\Work\monti\src\cd1\xzip\_$hex$t_header.xhd+box_zoom.png C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin
copy /b C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin+C:\Work\monti\src\cd1\xzip\_$hex$t_header.xhd+box_shadow_zoom.png C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin
copy /b C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin+C:\Work\monti\src\cd1\xzip\_$hex$t_header.xhd+box_shadow.png C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin
copy /b C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin+C:\Work\monti\src\cd1\xzip\_$hex$t_header.xhd+kasten.png C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin
copy /b C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin+C:\Work\monti\src\cd1\xzip\_$hex$t_header.xhd+kasten_zoom.png C:\Work\monti\src\cd1\xzip\_$hex$t_mul640.bin
cd C:\Work\monti\src\cd1\xzip
